print "LPTHW Lesson 5.2 \n \t Python format characters"

print '% :',  "This character marks the start of the specifier"

print 'd :', "Integer/decimal"
print 'i :', "Integer/decimal"
print 'o :', "Octal value"
print 'u :', "Obsolete type- identical to 'd' "
print 'x :', "Hexadecimal(uppercase)"
print 'e :', "Floating point exponential format(lowercase)"
print 'E :', "Floating point exponential format(uppercase)"
print 'f :', "Floating point decimal format"
print 'g :', "Floating point format(lowercase)"
print 'G :', "Floating point format(uppercse)"
print 'c :', "Single character ( accepts integer or single character string)"
print 'r :', "String (converts any Python object using repr())."
print 's :', "String (converts any Python object using str())."